### ISSUE TITLE
txnNotFound issue

### ISSUE THREAD

**Issue by aditya-stb** [XRPLF/xrpl-py#312] opened 2021-11-18 02:38 UTC
When using send_reliable_submission , xrpl it sometimes returns txnNotFound error. This is due to the fact that it calls submit transaction and fetch result by hash in quick succession which fails to find that transaction sometimes ( https://github.com/ripple/rippled/issues/2828 )

**Comment by JST5000** [comment] 2021-11-18 21:27
Do you happen to have a stack trace of the error or code snippet which can reproduce the problem?

**Comment by mvadari** [comment] 2021-11-23 00:45
It doesn't actually call in quick succession - there is a 4-second delay between submitting the transaction and retrieving it for the first time.

**Comment by JST5000** [comment] 2022-01-14 00:24
Closing as unable to reproduce - if you manage to reproduce happy to reopen! :)

**Comment by mvadari** [comment] 2022-01-14 00:27
Reopening because this is a race condition issue, and thus hard to reproduce. Here is the PR that fixes it in xrpl.js: https://github.com/XRPLF/xrpl.js/pull/1883

**Comment by brokeharvard** [comment] 2022-01-29 02:34
Would be great if we could get a fix for this incorporated into xrpl.py.   I'm receiving the txnNotFound error for every OfferCreate transaction I submit notwithstanding them actually showing up on the ledger.

**Comment by hammertoe** [comment] 2022-03-04 13:36
I'm getting this same failure too. Code that reproduces it:

```from pprint import pprint
from xrpl.clients import JsonRpcClient
from xrpl.wallet.main import Wallet
from xrpl.models.requests import AccountNFTs
from xrpl.models.transactions import Memo, NFTokenCancelOffer, NFTokenMint
from xrpl.transaction import safe_sign_and_autofill_transaction
from xrpl.transaction import send_reliable_submission
from xrpl.utils import drops_to_xrp, hex_to_str, str_to_hex


client = JsonRpcClient("http://xls20-sandbox.rippletest.net:51234")

# rBYSPwS3zvB2wu1nb5rxvU5gSuh5qgYW8V                                                                                                                           
wallet = Wallet("sh69ae5M5k7JhYpMmCoPVAz27456p", 0)

mint_args = {
    "account": "rBYSPwS3zvB2wu1nb5rxvU5gSuh5qgYW8V",
    "flags": 8,
    "uri": "",
    "memos": [Memo.from_dict({"memo_data": str_to_hex("Minted by Dealer")})],
    "transfer_fee": 0,
    "token_taxon": 0,
}

mint = NFTokenMint.from_dict(mint_args)
my_tx_payment_signed = safe_sign_and_autofill_transaction(mint, wallet, client)
tx_response = send_reliable_submission(my_tx_payment_signed, client)

pprint(tx_response)
```

Traceback:
```(venv) mhamilton@LON-DF3TBM-M demos % python cards-dealer.py
Traceback (most recent call last):
  File "cards-dealer.py", line 27, in <module>
    tx_response = send_reliable_submission(my_tx_payment_signed, client)
  File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/transaction/reliable_submission.py", line 32, in send_reliable_submission
    return asyncio.run(async_send_reliable_submission(transaction, client))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/reliable_submission.py", line 93, in send_reliable_submission
    return await _wait_for_final_transaction_outcome(
  File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/reliable_submission.py", line 37, in _wait_for_final_transaction_outcome
    transaction_response = await get_transaction_from_hash(transaction_hash, client)
  File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/ledger.py", line 50, in get_transaction_from_hash
    raise XRPLRequestFailureException(response.result)
xrpl.asyncio.clients.exceptions.XRPLRequestFailureException: Request failed, txnNotFound: Transaction not found.
```

**Comment by khancode** [comment] 2022-04-25 19:55
> I'm getting this same failure too. Code that reproduces it:
> 
> ```
> from xrpl.clients import JsonRpcClient
> from xrpl.wallet.main import Wallet
> from xrpl.models.requests import AccountNFTs
> from xrpl.models.transactions import Memo, NFTokenCancelOffer, NFTokenMint
> from xrpl.transaction import safe_sign_and_autofill_transaction
> from xrpl.transaction import send_reliable_submission
> from xrpl.utils import drops_to_xrp, hex_to_str, str_to_hex
> 
> 
> client = JsonRpcClient("http://xls20-sandbox.rippletest.net:51234")
> 
> # rBYSPwS3zvB2wu1nb5rxvU5gSuh5qgYW8V                                                                                                                           
> wallet = Wallet("sh69ae5M5k7JhYpMmCoPVAz27456p", 0)
> 
> mint_args = {
>     "account": "rBYSPwS3zvB2wu1nb5rxvU5gSuh5qgYW8V",
>     "flags": 8,
>     "uri": "",
>     "memos": [Memo.from_dict({"memo_data": str_to_hex("Minted by Dealer")})],
>     "transfer_fee": 0,
>     "token_taxon": 0,
> }
> 
> mint = NFTokenMint.from_dict(mint_args)
> my_tx_payment_signed = safe_sign_and_autofill_transaction(mint, wallet, client)
> tx_response = send_reliable_submission(my_tx_payment_signed, client)
> 
> pprint(tx_response)
> ```
> 
> Traceback:
> 
> ```
> Traceback (most recent call last):
>   File "cards-dealer.py", line 27, in <module>
>     tx_response = send_reliable_submission(my_tx_payment_signed, client)
>   File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/transaction/reliable_submission.py", line 32, in send_reliable_submission
>     return asyncio.run(async_send_reliable_submission(transaction, client))
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/reliable_submission.py", line 93, in send_reliable_submission
>     return await _wait_for_final_transaction_outcome(
>   File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/reliable_submission.py", line 37, in _wait_for_final_transaction_outcome
>     transaction_response = await get_transaction_from_hash(transaction_hash, client)
>   File "/Users/mhamilton/Development/demos/venv/lib/python3.8/site-packages/xrpl/asyncio/transaction/ledger.py", line 50, in get_transaction_from_hash
>     raise XRPLRequestFailureException(response.result)
> xrpl.asyncio.clients.exceptions.XRPLRequestFailureException: Request failed, txnNotFound: Transaction not found.
> ```

I debugged your code and found the submitted transaction's engine_result is `temMALFORMED`; so it looks like your transaction was malformed. I changed the `uri` param to be non-empty string and it worked:
```TypeScript
"uri": str_to_hex("NFT mint test")
```

Going to create a PR that verifies a submitted transaction is valid before waiting for its final outcome.

**Comment by khancode** [comment] 2022-04-26 16:39
Closing this issue. Feel free to reopen if you can still reproduce this issue.

**Closed by khancode** 2022-04-26 16:39 UTC

**Comment by jonathanlei** [comment] 2023-01-31 22:31
race condition issue checked and solved (4 api calls till raising error) https://github.com/XRPLF/xrpl-py/pull/500
